def char_menu(char_option):
    print("")
    print("             ==== CHOOSE YOUR CHARACTER ===              ")
    print("Character: " + char_option)
    print("-------------------------------------")
    print("| 1.   Warlock       | 2.   Witch    |")
    print("---------------------------------------")
    print("| 3.   Minion      | 4.   Spellcaster  |")
    print("--------------------------------------------")
    print("|              5.   Escape                  |")
    print("------------------------------------------")
