-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.accounts
(
    account_id integer NOT NULL,
    username text NOT NULL,
    user_email text NOT NULL,
    user_password text NOT NULL,
    artist_id integer,
    PRIMARY KEY (account_id)
);

CREATE TABLE public.albums
(
    album_id integer NOT NULL,
    album_title text NOT NULL,
    album_length integer NOT NULL,
    artwork_url text NOT NULL,
    num_of_songs integer NOT NULL,
    release_date date NOT NULL,
    PRIMARY KEY (album_id)
);

CREATE TABLE public.albums_artists
(
    album_id integer NOT NULL,
    artist_id integer NOT NULL,
    PRIMARY KEY (album_id, artist_id)
);

CREATE TABLE public.artists
(
    artist_id integer NOT NULL,
    artist_name text NOT NULL,
    artist_bio text,
    PRIMARY KEY (artist_id)
);

CREATE TABLE public.groups
(
    group_id integer NOT NULL,
    group_name text NOT NULL,
    PRIMARY KEY (group_id)
);

CREATE TABLE public.groups_artists
(
    group_id integer NOT NULL,
    artist_id integer NOT NULL,
    PRIMARY KEY (group_id, artist_id)
);

CREATE TABLE public.songs
(
    song_id integer NOT NULL,
    song_title text NOT NULL,
    song_writer text NOT NULL,
    song_producer text NOT NULL,
    song_length integer NOT NULL,
    release_date date NOT NULL,
    album_id integer,
    PRIMARY KEY (song_id)
);

CREATE TABLE public.songs_artists
(
    song_id integer NOT NULL,
    artist_id integer NOT NULL,
    PRIMARY KEY (song_id, artist_id)
);

ALTER TABLE public.accounts
    ADD FOREIGN KEY (artist_id)
    REFERENCES public.artists (artist_id)
    NOT VALID;


ALTER TABLE public.albums_artists
    ADD FOREIGN KEY (album_id)
    REFERENCES public.albums (album_id)
    NOT VALID;


ALTER TABLE public.albums_artists
    ADD FOREIGN KEY (artist_id)
    REFERENCES public.artists (artist_id)
    NOT VALID;


ALTER TABLE public.groups_artists
    ADD FOREIGN KEY (artist_id)
    REFERENCES public.artists (artist_id)
    NOT VALID;


ALTER TABLE public.groups_artists
    ADD FOREIGN KEY (group_id)
    REFERENCES public.groups (group_id)
    NOT VALID;


ALTER TABLE public.songs
    ADD FOREIGN KEY (album_id)
    REFERENCES public.albums (album_id)
    NOT VALID;


ALTER TABLE public.songs_artists
    ADD FOREIGN KEY (artist_id)
    REFERENCES public.artists (artist_id)
    NOT VALID;


ALTER TABLE public.songs_artists
    ADD FOREIGN KEY (song_id)
    REFERENCES public.songs (song_id)
    NOT VALID;

END;